[package]
name = "osm-pbf-proto"
version = "0.1.0-alpha.3"
description = "OpenStreetMap PBF-Format data-structures"
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
keywords = ["osm", "openstreetmaps", "pbf", "protobuf", "osm-pbf"]
readme = "README.md"

[dependencies]
protobuf = "3.3.0"

[build-dependencies]
protobuf-codegen = "3.3.0"
